name: Process honors images

on:
  push:
    paths:
      - 'assets/honors/**'
      - 'tools/process_images.py'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Process images
        run: python tools/process_images.py

      - name: Commit processed images (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto-process honors images"
            git push
          fi
